#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/1panel/apps/weather_forecast_server}"
DATA_DIR="${REFERENCE_DATA_DIR:-$APP_DIR/data/openmeteo_reference}"
IMAGE_NAME="${IMAGE_NAME:-weather-forecast-openmeteo:latest}"
CONTAINER_NAME="${REFERENCE_CONTAINER_NAME:-weather-forecast-openmeteo-reference}"
REFERENCE_PORT="${REFERENCE_PORT:-18082}"
OPENMETEO_UID="${WEATHER_OPENMETEO_UID:-999}"
OPENMETEO_GID="${WEATHER_OPENMETEO_GID:-999}"

REMOTE_DATA_DIRECTORY="${REMOTE_DATA_DIRECTORY:?Set REMOTE_DATA_DIRECTORY to the fixed processed .om snapshot URL.}"
WEATHER_DEM_REMOTE_DATA_DIRECTORY="${WEATHER_DEM_REMOTE_DATA_DIRECTORY:?Set WEATHER_DEM_REMOTE_DATA_DIRECTORY to the matching DEM snapshot URL.}"
CACHE_SIZE="${CACHE_SIZE:-10GB}"
CACHE_META_SIZE="${CACHE_META_SIZE:-1MB}"
REMOTE_DATA_DIRECTORY_MINIMUM_AGE="${REMOTE_DATA_DIRECTORY_MINIMUM_AGE:-}"

mkdir -p "$DATA_DIR"
chown "$OPENMETEO_UID:$OPENMETEO_GID" "$DATA_DIR"

docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true

docker run -d \
  --name "$CONTAINER_NAME" \
  -p "127.0.0.1:${REFERENCE_PORT}:8080" \
  -v "$DATA_DIR:/app/data" \
  -e "REMOTE_DATA_DIRECTORY=$REMOTE_DATA_DIRECTORY" \
  -e "REMOTE_DATA_DIRECTORY_MINIMUM_AGE=$REMOTE_DATA_DIRECTORY_MINIMUM_AGE" \
  -e "WEATHER_DEM_REMOTE_DATA_DIRECTORY=$WEATHER_DEM_REMOTE_DATA_DIRECTORY" \
  -e "CACHE_SIZE=$CACHE_SIZE" \
  -e "CACHE_META_SIZE=$CACHE_META_SIZE" \
  "$IMAGE_NAME" \
  serve --env production --hostname 0.0.0.0 --port 8080

docker ps --filter "name=$CONTAINER_NAME"
